pipeline {
  agent none
  stages {
    stage('Build'){
      agent {
        docker {
          image 'python:2-alpine'
        }  
    }
    steps {
      sh "sudo chown root:jenkins /run/docker.sock"
      sh 'python -m py_compile sources/add2vals.py sources/calc.py'
    }  
   }
  }  
}
